### ISSUE TITLE
Is it possible to use other vocoders?

### ISSUE THREAD

**Issue by nmichaud** [janvainer/speedyspeech#20]
Hi, I was wondering if it was possible to use other vocoders like MB-Melgan or Parallel-WaveGAN? For example, i've been trying to use the pre-trained models from https://github.com/kan-bayashi/ParallelWaveGAN but the spectrograms from Speedyspeech don't seem to match the expected format. Thanks!

**Comment by janvainer** [comment]
Hi, it is very hard to guarantee compatibility with other vocoders since other projects may simply use different features. You can compare the methods that create the features and their hyperparameters. If there is a difference in something like scaling etc, it should be possible to rescale the output of SpeedySpeech and get good results. Otherwise, you would probably have to either retrain speedy speech to use different features or retrain your vocoder to work with SpeedySpeech.

Do you have a list of most common feature extractors for different vocoder projects? Maybe it could be worth it to create several SpeedySpeech checkpoints for specific vocoders :)

**Comment by nmichaud** [comment]
OK thanks, that makes sense. Let me see if I can retrain speedyspeech for some of the newer vocoders.

**Comment by janvainer** [comment]
Great! Let me know how its going.

**Comment by dodoproptit99** [comment]
I think you can try HifiGAN for vocoder. Input of HifiGAN use the same feature with output of SpeedySpeech.

**Comment by janvainer** [comment]
Thanks for the tip. I will check it out. Could you recommend a reliable implementation?

**Comment by dodoproptit99** [comment]
I have some adjustments from this repository ([hifiGAN](https://github.com/jik876/hifi-gan)) for my Vietnamese dataset. It's pretty easy to retrain :D

**Comment by janvainer** [comment]
Wow the repo looks pretty simple! :) How long did you train it and how well it adapted to Vietnamese?
